[package]
name = "parabox-terminal"
version = "0.1.0"
edition = "2024"
license = "UNLICENSED"
publish = false

[lib]
name = "parabox_terminal"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[[bin]]
name = "parabox"
path = "src/bin/client.rs"

[[bin]]
name = "parabox-server"
path = "src/main.rs"

[[bin]]
name = "parabox-verifier"
path = "src/bin/verifier.rs"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
